### ISSUE TITLE
Build crash when it reached RidiculousFemaleCompanion.esp

### ISSUE THREAD

**Issue by VeryGoodSauce** [focustense/easymod#149]
I got halfway through building, after only 1 error was identified beforehand. The app crashed while applying face customizations to the RidiculousFemaleCompanion.esp, which I'm in no way attached to so will try rebuilding with it disabled/deleted.

[Log_20220525_023634_6002137.txt](https://github.com/focustense/easymod/files/8770015/Log_20220525_023634_6002137.txt)
![EasyNPC_crash](https://user-images.githubusercontent.com/81716817/170236961-2ad91e51-b9ba-436f-a1fa-88dbf8b8c0b5.png)

**Comment by focustense** [comment]
One of your plugins is referencing an invalid head part (meaning, nothing in your LO defines a head part with that ID).

```
2022-05-25 02:57:38.250 -07:00 [87] [DBG] Apply Face Customizations -> 0RFC_Sexica 'Sexica' (005900:RidiculousFemaleCompanion.esp)
2022-05-25 02:57:38.258 -07:00 [87] [DBG] Importing shallow overrides from Sexica.esp
2022-05-25 02:57:38.265 -07:00 [87] [DBG] Importing head parts from Sexica.esp
2022-05-25 02:57:38.272 -07:00 [87] [DBG] Clone requested for IHeadPartGetter (03D4D5:Dragonborn.esm)
2022-05-25 02:57:38.279 -07:00 [87] [DBG] Beginning clone for record 03D4D5:Dragonborn.esm
2022-05-25 02:57:38.286 -07:00 [87] [DBG] Clone completed for 03D4D5:Dragonborn.esm -> 00142C:NPC Appearances Merged.esp; performing additional setup
2022-05-25 02:57:38.293 -07:00 [87] [DBG] Processing head part 00142C:NPC Appearances Merged.esp 'AAA_Hair_Valmari' for cloning
2022-05-25 02:57:38.299 -07:00 [87] [DBG] Clone requested for IFormListGetter (107B9A:Skyrim.esm)
2022-05-25 02:57:38.306 -07:00 [87] [DBG] Record 107B9A:Skyrim.esm is already provided by the merged plugin's masters.
2022-05-25 02:57:38.420 -07:00 [87] [DBG] Clone requested for IHeadPartGetter (03D4D3:Dragonborn.esm)
2022-05-25 02:57:38.423 -07:00 [87] [DBG] Beginning clone for record 03D4D3:Dragonborn.esm
2022-05-25 02:57:38.427 -07:00 [01] [INF] Task 'Apply Face Customizations' ended with status "Faulted"
2022-05-25 02:57:38.431 -07:00 [01] [ERR] Task 'Apply Face Customizations' failed due to an unhandled exception
System.AggregateException: One or more errors occurred. (Could not resolve record)
 ---> RecordException Dragonborn.esm => 03D4D3:Dragonborn.esm<HeadPart>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 setup)
```

What's puzzling is that EasyNPC normally does a scan at startup and will disable any options that would reference an invalid head part. That feature was added specifically because this issue kept coming up. Possibly, you had a load order that used to be valid, but you upgraded one of the mods in that load order and it's no longer compatible with the version in use?

Another thing I'm having trouble figuring out is why it would be trying to clone a headpart in Dragonborn.esm, as it never clones anything vanilla. Can you see what these plugins (`RidiculousFemaleCompanion.esp` and `Sexica.esp`) look like in xEdit? What head parts does the NPC actually use, does it have something like an "injected" record that is italicized in xEdit?

I wonder if this is an Anniversary Edition problem - haven't seen any of those reported on Discord yet, but if you're using a plugin designed for SE and actually running AE (or vice versa) then maybe the form IDs don't match.
