### ISSUE TITLE
Packing BSA Archive Catastrophic Failure

### ISSUE THREAD

**Issue by omarbirjas** [focustense/easymod#156]
I have no clue what's wrong, all I know is that I have a log file. I have 3 suspicious masters but they don't seem like issues. The entire build fails. The meshes folder does not get created in the mod folder, that was the initial error.
[Log_20220721_015525_0755763.txt](https://github.com/focustense/easymod/files/9156938/Log_20220721_015525_0755763.txt)
.

**Comment by focustense** [comment]
This is the error:

```
2022-07-21 01:55:56.197 -05:00 [01] [ERR] Exception was not handled
Focus.Apps.EasyNpc.Build.BuildException: Task 'Pack BSA Archive' (Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask) failed to complete
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\Games\Nexus Mod Manager\SkyrimSE\Mods\NPC Merge 2022-07-21\meshes'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Games\Nexus Mod Manager\SkyrimSE\Mods\NPC Merge 2022-07-21\meshes'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
```

It means your merge didn't generate any meshes, which is almost certainly not intended. If it didn't crash, you'd have an unusable mod regardless.

What does your pre-build look like, are there any errors or warnings? Also, does your mod list include any NPC visual overhauls? (I kind of just skimmed the log, but I didn't actually see any)
