### ISSUE TITLE
Bug while building

### ISSUE THREAD

**Issue by SPAS79** [focustense/easymod#160]
2022-09-18 12:16:16.761 +02:00 [01] [INF] Initialized: EasyNPC version 0.9.5.0, built on "2021-10-10T23:41:30.5657418Z"
2022-09-18 12:16:16.890 +02:00 [01] [INF] Using game data directory: D:\SteamLib\steamapps\common\Skyrim Special Edition\Data
2022-09-18 12:17:20.561 +02:00 [01] [INF] Load order confirmed
2022-09-18 12:17:20.566 +02:00 [01] [INF] Creating load order analyzer
2022-09-18 12:17:21.311 +02:00 [07] [INF] Beginning load order analysis
2022-09-18 12:17:21.326 +02:00 [19] [INF] Starting analysis of Dawnguard.esm
2022-09-18 12:17:21.326 +02:00 [06] [INF] Starting analysis of ccBGSSSE037-Curios.esl
2022-09-18 12:17:21.326 +02:00 [17] [INF] Starting analysis of ccQDRSSE001-SurvivalMode.esl
2022-09-18 12:17:21.326 +02:00 [14] [INF] Starting analysis of Dragonborn.esm
2022-09-18 12:17:21.326 +02:00 [12] [INF] Starting analysis of HearthFires.esm
2022-09-18 12:17:21.326 +02:00 [25] [INF] Starting analysis of ccBGSSSE001-Fish.esm
2022-09-18 12:17:21.326 +02:00 [18] [INF] Starting analysis of Skyrim.esm
2022-09-18 12:17:21.326 +02:00 [22] [INF] Starting analysis of ccBGSSSE025-AdvDSGS.esm
2022-09-18 12:17:21.326 +02:00 [07] [INF] Starting analysis of Update.esm
2022-09-18 12:17:21.342 +02:00 [17] [INF] Completed analysis of ccQDRSSE001-SurvivalMode.esl
2022-09-18 12:17:21.342 +02:00 [06] [INF] Completed analysis of ccBGSSSE037-Curios.esl
2022-09-18 12:17:21.480 +02:00 [25] [INF] Completed analysis of ccBGSSSE001-Fish.esm
2022-09-18 12:17:21.501 +02:00 [22] [INF] Completed analysis of ccBGSSSE025-AdvDSGS.esm
2022-09-18 12:17:21.504 +02:00 [12] [INF] Completed analysis of HearthFires.esm
2022-09-18 12:17:21.505 +02:00 [07] [INF] Completed analysis of Update.esm
2022-09-18 12:17:21.591 +02:00 [14] [INF] Completed analysis of Dragonborn.esm
2022-09-18 12:17:21.593 +02:00 [19] [INF] Completed analysis of Dawnguard.esm
2022-09-18 12:17:21.842 +02:00 [18] [INF] Completed analysis of Skyrim.esm
2022-09-18 12:17:21.843 +02:00 [07] [INF] Analysis completed in 0.52 sec
2022-09-18 12:18:37.994 +02:00 [01] [INF] Build started
2022-09-18 12:18:38.000 +02:00 [01] [INF] Created task 'Initialize Patch'
2022-09-18 12:18:38.000 +02:00 [01] [INF] Created task 'Copy FaceGen Data'
2022-09-18 12:18:38.002 +02:00 [01] [INF] Attempting to start task 'Initialize Patch'
2022-09-18 12:18:38.002 +02:00 [01] [INF] Attempting to start task 'Copy FaceGen Data'
2022-09-18 12:18:38.005 +02:00 [17] [INF] Task 'Copy FaceGen Data' successfully started
2022-09-18 12:18:38.013 +02:00 [01] [INF] Task 'Copy FaceGen Data' ended with status "RanToCompletion"
2022-09-18 12:18:38.026 +02:00 [18] [INF] Task 'Initialize Patch' successfully started
2022-09-18 12:18:38.058 +02:00 [01] [INF] Task 'Initialize Patch' ended with status "RanToCompletion"
2022-09-18 12:18:38.058 +02:00 [01] [INF] Created task 'Import NPC Defaults'
2022-09-18 12:18:38.058 +02:00 [01] [INF] Attempting to start task 'Import NPC Defaults'
2022-09-18 12:18:38.058 +02:00 [44] [INF] Task 'Import NPC Defaults' successfully started
2022-09-18 12:18:38.391 +02:00 [18] [INF] Skipping LvlDraugrAmbushBossMale '' (0B7989:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.395 +02:00 [18] [INF] Skipping EncVampire06Template 'Volkihar Vampire' (033852:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.395 +02:00 [18] [INF] Skipping EncVampire05Template 'Ancient Vampire' (033851:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.395 +02:00 [18] [INF] Skipping EncVampire04Template 'Vampire Nightstalker' (033850:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.395 +02:00 [18] [INF] Skipping EncVampire03Template 'Vampire Mistwalker' (03384F:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.395 +02:00 [18] [INF] Skipping EncVampire02Template 'Blooded Vampire' (03384E:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.395 +02:00 [18] [INF] Skipping EncVampire01Template 'Vampire' (032FE8:Skyrim.esm) because all overrides use the same template.
2022-09-18 12:18:38.401 +02:00 [01] [INF] Task 'Import NPC Defaults' ended with status "RanToCompletion"
2022-09-18 12:18:38.401 +02:00 [01] [INF] Created task 'Apply Face Customizations'
2022-09-18 12:18:38.401 +02:00 [01] [INF] Attempting to start task 'Apply Face Customizations'
2022-09-18 12:18:38.401 +02:00 [18] [INF] Task 'Apply Face Customizations' successfully started
2022-09-18 12:18:38.424 +02:00 [43] [WRN] Unable to find the template 01C1A0:Skyrim.esm for NPC dunBluePalaceMareMaiden 'Sultry Maiden' (09F83A:Skyrim.esm) in the current profile. Traits cannot be copied and this character may be bugged in game.
2022-09-18 12:18:38.425 +02:00 [01] [INF] Task 'Apply Face Customizations' ended with status "RanToCompletion"
2022-09-18 12:18:38.425 +02:00 [01] [INF] Created task 'De-wiggify Records'
2022-09-18 12:18:38.425 +02:00 [01] [INF] Attempting to start task 'De-wiggify Records'
2022-09-18 12:18:38.425 +02:00 [43] [INF] Task 'De-wiggify Records' successfully started
2022-09-18 12:18:38.431 +02:00 [01] [INF] Task 'De-wiggify Records' ended with status "RanToCompletion"
2022-09-18 12:18:38.431 +02:00 [01] [INF] Created task 'Save Patch'
2022-09-18 12:18:38.431 +02:00 [01] [INF] Created task 'De-wiggify FaceGens'
2022-09-18 12:18:38.431 +02:00 [01] [INF] Attempting to start task 'Save Patch'
2022-09-18 12:18:38.431 +02:00 [01] [INF] Attempting to start task 'De-wiggify FaceGens'
2022-09-18 12:18:38.432 +02:00 [11] [INF] Task 'Save Patch' successfully started
2022-09-18 12:18:38.433 +02:00 [43] [INF] Task 'De-wiggify FaceGens' successfully started
2022-09-18 12:18:38.441 +02:00 [01] [INF] Task 'De-wiggify FaceGens' ended with status "RanToCompletion"
2022-09-18 12:18:38.512 +02:00 [01] [INF] Task 'Save Patch' ended with status "RanToCompletion"
2022-09-18 12:18:38.512 +02:00 [01] [INF] Created task 'Copy Shared Resources'
2022-09-18 12:18:38.512 +02:00 [01] [INF] Attempting to start task 'Copy Shared Resources'
2022-09-18 12:18:38.512 +02:00 [42] [INF] Task 'Copy Shared Resources' successfully started
2022-09-18 12:18:38.518 +02:00 [01] [INF] Task 'Copy Shared Resources' ended with status "RanToCompletion"
2022-09-18 12:18:38.518 +02:00 [01] [INF] Created task 'Extract Texture Paths'
2022-09-18 12:18:38.518 +02:00 [01] [INF] Attempting to start task 'Extract Texture Paths'
2022-09-18 12:18:38.519 +02:00 [20] [INF] Task 'Extract Texture Paths' successfully started
2022-09-18 12:18:38.524 +02:00 [01] [INF] Task 'Extract Texture Paths' ended with status "RanToCompletion"
2022-09-18 12:18:38.525 +02:00 [01] [INF] Created task 'Copy Textures'
2022-09-18 12:18:38.525 +02:00 [01] [INF] Attempting to start task 'Copy Textures'
2022-09-18 12:18:38.525 +02:00 [20] [INF] Task 'Copy Textures' successfully started
2022-09-18 12:18:38.538 +02:00 [01] [INF] Task 'Copy Textures' ended with status "RanToCompletion"
2022-09-18 12:18:38.539 +02:00 [01] [INF] Created task 'Pack BSA Archive'
2022-09-18 12:18:38.539 +02:00 [01] [INF] Attempting to start task 'Pack BSA Archive'
2022-09-18 12:18:38.547 +02:00 [15] [INF] Task 'Pack BSA Archive' successfully started
2022-09-18 12:18:38.553 +02:00 [01] [INF] Task 'Pack BSA Archive' ended with status "Faulted"
2022-09-18 12:18:38.553 +02:00 [01] [ERR] Task 'Pack BSA Archive' failed due to an unhandled exception
System.AggregateException: One or more errors occurred. (Could not find a part of the path 'D:\VORTEXMODS for SkyrimVR\NPC Merge 2022-09-18\meshes'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\VORTEXMODS for SkyrimVR\NPC Merge 2022-09-18\meshes'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Focus.Storage.Archives.ArchiveBuilder.AddDirectory(String directoryName, String pathInArchive, String searchPattern)
   at Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask.BuildFilteredArchive(String outputDirectory, ArchiveSettings settings)
   at Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask.<>c__DisplayClass11_0.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask.Run(BuildSettings settings)
   at Focus.Apps.EasyNpc.Build.Pipeline.BuildTask`1.Start(BuildSettings settings)
   at Focus.Apps.EasyNpc.Build.Pipeline.BuildInstance`2.<>c__DisplayClass27_0.<<StartAndWatch>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
2022-09-18 12:18:38.558 +02:00 [01] [INF] All tasks ended
2022-09-18 12:18:38.560 +02:00 [01] [INF] Cleanup succeeded, build has ended.
2022-09-18 12:18:38.561 +02:00 [01] [ERR] Exception was not handled
Focus.Apps.EasyNpc.Build.BuildException: Task 'Pack BSA Archive' (Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask) failed to complete
 ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path 'D:\VORTEXMODS for SkyrimVR\NPC Merge 2022-09-18\meshes'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\VORTEXMODS for SkyrimVR\NPC Merge 2022-09-18\meshes'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Focus.Storage.Archives.ArchiveBuilder.AddDirectory(String directoryName, String pathInArchive, String searchPattern)
   at Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask.BuildFilteredArchive(String outputDirectory, ArchiveSettings settings)
   at Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask.<>c__DisplayClass11_0.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Focus.Apps.EasyNpc.Build.Pipeline.ArchiveCreationTask.Run(BuildSettings settings)
   at Focus.Apps.EasyNpc.Build.Pipeline.BuildTask`1.Start(BuildSettings settings)
   at Focus.Apps.EasyNpc.Build.Pipeline.BuildInstance`2.<>c__DisplayClass27_0.<<StartAndWatch>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Focus.Apps.EasyNpc.Build.BuildViewModel.BeginBuild()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Focus.Apps.EasyNpc.App.Main()

**Comment by focustense** [comment]
```
System.AggregateException: One or more errors occurred. (Could not find a part of the path 'D:\VORTEXMODS for SkyrimVR\NPC Merge 2022-09-18\meshes'.)
---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\VORTEXMODS for SkyrimVR\NPC Merge 2022-09-18\meshes'.
at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator1.Init()
```

Looks like it's trying to create a BSA without any meshes. Probably it should handle this edge case and not crash. However, if your merge has no meshes, then it has no facegen files, which means with nearly 100% certainty that something else is set up incorrectly. Either there are no mods to merge, or the mod directory is wrong and it can't find any assets.

Is `D:\VORTEXMODS for SkyrimVR` the correct path in this case? Is that the actual Vortex staging directory where all other mods are located? What else is in that directory (can you give just a couple of examples)?

**Comment by SPAS79** [comment]
Yes that is the staging folders, I have no idea if the image attachment will work but here goes... 
![image](https://user-images.githubusercontent.com/13502898/191809372-63d48919-2751-43c3-8fd5-359e6ffe480a.png)
