### ISSUE TITLE
Errors while starting EasyNPC

### ISSUE THREAD

**Issue by ButchDiavolo** [focustense/easymod#175]
Hi, I updated to the latest EasyNPC. I had no problems what so ever with the previous version, but this time I get an error message for 4 files, including Skyrim itself? When I soldier on and attempt to create a merge, EasyNPC stops and creates an error log. I have tried twice, so I will attach 2 separate error logs.
I am hoping you can help me figure out what the problem is.
[Log_20230118_175608_6111724.txt](https://github.com/focustense/easymod/files/10448997/Log_20230118_175608_6111724.txt)
[Log_20230118_181421_7133249.txt](https://github.com/focustense/easymod/files/10448998/Log_20230118_181421_7133249.txt)

**Comment by focustense** [comment]
```
2023-01-18 17:56:18.778 +01:00 [24] [ERR] Analysis failed for MoreNastyCritters.esp
System.ArgumentException: BOD2 type not expected on versions < 43
   at Mutagen.Bethesda.Skyrim.Internals.BodyTemplateBinaryOverlay.CustomFactory(OverlayStream stream, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.GetBodyTemplateCustom()
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.ArmorAddonHelper.ReplacesHair(IArmorAddonGetter addon)
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.<>c__DisplayClass20_0.<GetWigInfo>b__4(IArmorAddonGetter x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.GetWigInfo(INpcGetter npc)
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.Analyze(String pluginName, IRecordKey key)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Focus.Analysis.Records.RecordAnalysisGroup`1..ctor(RecordType type, IEnumerable`1 records)
   at Focus.Analysis.Execution.AnalysisRunner.<>c__DisplayClass15_0`1.<MakeAnalyzerAction>b__0(String pluginName, IEnumerable`1 keys)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Focus.Analysis.Execution.AnalysisRunner.RunForPlugin(String pluginName)
```

You have an LE mod in your load order that's been improperly converted to SE. Conversion requires upgrading the mod in Creation Kit, not just changing the form version.

It might be this `MoreNastyCritters.esp` mod, but I can't be sure of that because these bad conversions can throw exceptions implicitly, when Mutagen tries to get the list of override records, etc. I'd start by looking at the mod above, but if that's not the culprit then you'll have to do your own digging, or check using other tools like xEdit.

**Comment by focustense** [comment]
Actually, reading the error a second time, I can see that it's the opposite way around - the mod has SE data but is reporting an LE form version. Still the same basic issue though, whichever mod is responsible has records that are inconsistent with its version.

**Comment by ButchDiavolo** [comment]
> Actually, reading the error a second time, I can see that it's the opposite way around - the mod has SE data but is reporting an LE form version. Still the same basic issue though, whichever mod is responsible has records that are inconsistent with its version.

That was indeed the problem.  I had in fact several badly converted mods in my loadlist. Converting them myself the right way solved the problems. Thank you for your help!
