### ISSUE TITLE
Crash on Apply Face Customizations

### ISSUE THREAD

**Issue by NinaMercer** [focustense/easymod#176]
[Log_20230120_004414_6550746.txt](https://github.com/focustense/easymod/files/10464603/Log_20230120_004414_6550746.txt)

Exactly as the title says...

**Comment by focustense** [comment]
Bad mod conversion:

```
2023-01-20 00:44:19.446 -08:00 [18] [INF] Starting analysis of HornyCreatures.esp
2023-01-20 00:44:19.450 -08:00 [18] [ERR] Analysis failed for HornyCreatures.esp
System.ArgumentException: BOD2 type not expected on versions < 43
   at Mutagen.Bethesda.Skyrim.Internals.BodyTemplateBinaryOverlay.CustomFactory(OverlayStream stream, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.GetBodyTemplateCustom()
   at Mutagen.Bethesda.Skyrim.Internals.ArmorAddonBinaryOverlay.get_BodyTemplate()
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.ArmorAddonHelper.ReplacesHair(IArmorAddonGetter addon)
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.<>c__DisplayClass20_0.<GetWigInfo>b__4(IArmorAddonGetter x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.GetWigInfo(INpcGetter npc)
   at Focus.Providers.Mutagen.Analysis.NpcAnalyzer.Analyze(String pluginName, IRecordKey key)
   at Focus.Analysis.Execution.AnalysisRunner.<>c__DisplayClass15_1`1.<MakeAnalyzerAction>b__1(IRecordKey key)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Focus.Analysis.Records.RecordAnalysisGroup`1..ctor(RecordType type, IEnumerable`1 records)
   at Focus.Analysis.Execution.AnalysisRunner.<>c__DisplayClass15_0`1.<MakeAnalyzerAction>b__0(String pluginName, IEnumerable`1 keys)
   at Focus.Analysis.Execution.AnalysisRunner.<>c__DisplayClass16_0.<RunForPlugin>b__4(<>f__AnonymousType1`2 <>h__TransparentIdentifier1)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Focus.Analysis.Execution.AnalysisRunner.RunForPlugin(String pluginName)
```

You have an LE mod that's been improperly converted to SE. This is the same issue as #175, in which a mod has had its Body Template updated to SE but still has the old form version. It _might_ be the specific mod in the trace above, but unfortunately these errors can pop up at odd and unexpected times, whenever Mutagen decides to look in a mod, and it doesn't accurately report the source, so you may have to comb through your mod list to find all possible culprits.

Unfortunately there's nothing EasyNPC can do about this since it's Mutagen that throws the exception and it does so when simply reading the record, so other than reading every single AA from every mod on startup, there's no way to detect these ahead of time. Although I might see in the future about trying to wrap this in a more meaningful error message so it's not necessary to read the log.
