### ISSUE TITLE
after running build the app halted with an unexpected error 

### ISSUE THREAD

**Issue by AttilaGM** [focustense/easymod#184]
[Log_20230519_191225_6668900.zip](https://github.com/focustense/easymod/files/11521050/Log_20230519_191225_6668900.zip)
This is my log file. Hopefully you can open the zip file, if not, I can upload the unzipped file instead. 
Thx Attila

**Comment by focustense** [comment]
```
 ---> RecordException Dragonborn.esm => 03D4D3:Dragonborn.esm<HeadPart>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 defaultSetup, Action`1 masterSetup)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.<>c__DisplayClass27_0`2.<ReplaceList>b__0(IFormLinkGetter`1 x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.ReplaceList[T,TGetter](ExtendedList`1 list, IGroup`1 group, Action`1 setup)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.ImportHeadPartDependencies(HeadPart headPart)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.<Import>b__13_0[T,TGetter](T x)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 defaultSetup, Action`1 masterSetup)
   at Focus.Apps.EasyNpc.Build.Pipeline.RecordImporter.Import[T,TGetter](IFormLinkGetter`1 link, Func`2 groupSelector)
   at Focus.Apps.EasyNpc.Build.Pipeline.NpcFacesTask.<>c__DisplayClass7_0.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

One of your plugins has a head part pointing to a nonexistent form ID. Can't really tell exactly which one from the log, you'd have to open your load order in xEdit and navigate to this record to see which mod(s) are overriding that record.
