### ISSUE TITLE
Getting "Something Went Wrong" error when trying to run APP

### ISSUE THREAD

**Issue by Faroh3K** [focustense/easymod#188]
Simply disabled mod AIO's and Patches, then went to run EasyNPC and the error popped up. 
Attached is the log file I was told to submit.

[Log_20231120_215826_7507505.txt](https://github.com/focustense/easymod/files/13421335/Log_20231120_215826_7507505.txt)

**Comment by focustense** [comment]
The error makes it pretty clear that one of your plugins is broken:

```
 ---> RecordException KJ Lore Tattoos 4K.esp => : Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Cannot move position past the length of the stream
   at Noggog.BinaryReadStream.SetPosition(Int64 pos)
   at Noggog.BinaryReadStream.set_Position(Int64 value)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillModTypes(IBinaryReadStream stream, ModTypeFillWrapper fill, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModBinaryOverlay.SkyrimModFactory(IMutagenReadStream stream, ModKey modKey, SkyrimRelease release, Boolean shouldDispose)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModBinaryOverlay.SkyrimModFactory(ModPath path, SkyrimRelease release, StringsReadParameters stringsParam, IFileSystem fileSystem)
   --- End of inner exception stack trace ---
```

Try deactivating "KJ Lore Tattoos 4K.esp", or maybe running it through xEdit to see if it can detect/fix whatever problem is there.
