### ISSUE TITLE
Crash I dont know what caused it. Any help will be very appreciated 

### ISSUE THREAD

**Issue by Asumcc** [focustense/easymod#189]
[Log_20231121_163708_0902115.txt](https://github.com/focustense/easymod/files/13424317/Log_20231121_163708_0902115.txt)

**Comment by Asumcc** [comment]
It keep failing during copy texture

**Comment by focustense** [comment]
Looks like Mutagen doesn't think your BSA is a valid archive:

```
2023-11-21 16:37:33.607 +08:00 [24] [ERR] Problem reading from archive D:\Game\Vortex Staging Folder MOds\JK's College of Winterhold-65676-1-1-1685005336\JK's College of Winterhold.bsa
ArchiveException D:\Game\Vortex Staging Folder MOds\JK's College of Winterhold-65676-1-1-1685005336\JK's College of Winterhold.bsa: Archive is not a BSA    at Mutagen.Bethesda.Archives.Bsa.BsaReader..ctor(Func`1 streamGetter, Nullable`1 pathHint)
   at Mutagen.Bethesda.Archives.Bsa.BsaReader..ctor(FilePath path, IFileSystem fileSystem)
   at Mutagen.Bethesda.Archives.DI.ArchiveReaderProvider.Create(FilePath path)
   at Focus.Providers.Mutagen.MutagenArchiveProvider.<>c__DisplayClass13_0.<GetReader>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Focus.Providers.Mutagen.MutagenArchiveProvider.<>c__DisplayClass8_0.<GetArchiveFileNames>b__0()
   at Focus.Providers.Mutagen.MutagenArchiveProvider.Safe[T](String archivePath, Func`1 action)
```

Have you tried opening `JK's College of Winterhold.bsa` in a tool like BSArch or [BSA Browser](https://github.com/AlexxEG/BSA_Browser)?

**Comment by Asumcc** [comment]
Sorry for the late reply, I do not use github frequently. I have already fixed it by resetting the npc default back to the original and change only the faces and doesnt play with (set as default) unless I actually know what I am doing. The JK College does not have any problem with the making of npc faces, Ive already succesfully finish it with JK Enabled.
