### ISSUE TITLE
Crashing on launch.

### ISSUE THREAD

**Issue by efvalentine99** [focustense/easymod#197]
Hi! I am not sure what to do or where I've gone wrong. I've followed the instructions and only launch from the launcher extension on Vortex. But I haven't been able to even toy with it because it immediately crashes/gives this log when I launch it. Here is the log: 
[Log_20240311_211314_1916575.txt](https://github.com/focustense/easymod/files/14566386/Log_20240311_211314_1916575.txt)

**Comment by focustense** [comment]
There seems to be something wrong with your Vortex deployment because it says that some plugins in your load order are not found:

```
2024-03-11 21:13:14.360 -05:00 [01] [INF] Initialized: EasyNPC version 0.9.6.0, built on "2022-11-10T01:44:14.6363051Z"
2024-03-11 21:13:14.622 -05:00 [01] [INF] Using game data directory: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data
2024-03-11 21:13:15.355 -05:00 [01] [WRN] Plugin AX ValSerano-CC.esp appears to be corrupt and cannot be loaded.
System.IO.FileNotFoundException: Could not find file 'c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\AX ValSerano-CC.esp'.
File name: 'c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\AX ValSerano-CC.esp'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at System.IO.Abstractions.FileWrapper.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at Focus.Providers.Mutagen.GameSetup.TryGetMasterNames(String dataDirectory, String pluginFileName)
```

I'm not sure if that's the root cause or an unrelated error. The crash happens a bit later:

```
Newtonsoft.Json.JsonSerializationException: Error converting value "Skyrim.esm" to type 'Focus.Apps.EasyNpc.Profiles.ProfileEvent'. Path '', line 1, position 12.
 ---> System.ArgumentException: Could not cast or convert from System.String to Focus.Apps.EasyNpc.Profiles.ProfileEvent.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
```

Which means your `profile.log` file is corrupt. If this is your first time trying to run the app, I would just delete it (from `%LocalAppData%\EasyNPC` and start over.

I have no guess as to how the corruption happened, unless it's related to the other warnings. No one else has reported a similar issue.

**Comment by efvalentine99** [comment]
Ahh, thank you so much!! I will re-install it fresh (and also check out those plugins, thanks!) and come back to comment if that fixes it, hopefully so!

**Comment by focustense** [comment]
Didn't say to reinstall. Reinstalling the app does nothing. Profile and other app data is stored in the local app data directory as I mentioned above.
