### ISSUE TITLE
Error in File.Delete when starting build

### ISSUE THREAD

**Issue by focustense** [focustense/easymod#31]
Log file from report:

```
2021-07-17 19:48:19.196 +02:00 [INF] All NPCs loaded.
2021-07-17 19:49:36.644 +02:00 [INF] [Pack Archive] - Waiting for merged folder
2021-07-17 19:49:36.644 +02:00 [INF] [Merged Plugin] - Not started
2021-07-17 19:49:36.644 +02:00 [INF] [Merged Folder] - Waiting for merged plugin
2021-07-17 19:49:36.648 +02:00 [ERR] Exception was not handled
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.File.Delete(String path)
   at Focus.Apps.EasyNpc.Build.BuildViewModel`1.<BeginBuild>b__79_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Focus.Apps.EasyNpc.Build.BuildViewModel`1.BeginBuild()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Focus.Apps.EasyNpc.App.Main()
```

This looks to be the build report for Vortex. It's probably failing because it doesn't exist when running from Mod Organizer.

Mistaken assumption that `File.Delete` would have an implicit "if exists". It doesn't.

**Comment by focustense** [comment]
Misinterpreted the original log. It's not that the file doesn't exist, and `File.Delete` **does** handle that. The problem is that the setting (`BuildReportPath`) is empty. This should never be the case and I'm looking into why.
