### ISSUE TITLE
Crash at Initial Opening of Program

### ISSUE THREAD

**Issue by smbecket** [focustense/easymod#36]
Program crashed when I tried to open it for the first time. Appears to be a problem with the Sands of Time mod. Log follows:

[Log_20210718_043859_4027903.txt](https://github.com/focustense/easymod/files/6835889/Log_20210718_043859_4027903.txt)

```
2021-07-18 04:38:59.540 -04:00 [INF] Initialized
2021-07-18 04:41:40.933 -04:00 [ERR] Exception was not handled
RecordException SOTFull.esp => 000D62:SOTFull.esp<Race>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.<GetValidRaces>b__41_0(IFormLinkGetter`1 x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.<ReadHairRecords>b__34_1(IHeadPartGetter x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Focus.Apps.EasyNpc.Main.LoaderViewModel`1.ConfirmPlugins()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Focus.Apps.EasyNpc.App.Main()
```

**Comment by focustense** [comment]
Edited your post for formatting, didn't change anything else.

This looks similar to an issue I saw in the past where an NPC didn't have any race declared, except in this case, it's pointing to a race that doesn't exist in the current load order. Usually that type of thing is missing masters, but current versions of EasyNPC should prevent loading with missing masters.

I can go grab this mod and check, but have you tried opening it in xEdit and seeing if it does in fact point to a valid race?

**Comment by smbecket** [comment]
Thank you for the quick response. I have to confess that my knowledge of
ssedit is rudimentary at best. Sands of Time is a very large mod (1.5 GB)
adding dozens of new enemies. I opened it in ssedit and under Race there
were 90 races listed under Name and quite a few more that were not listed
under Name. Most of them were ones I had seen before in the game but there
are a number that looked unique: Lola, Ice Bone Spirit, Witch Head, One Eye
Race, Invisible Race, Spirit. I assume some/all of these were developed for
Sands of Time and have no counterpart in regular Skyrim. I hope this is
some help but I would recommend you take a look for yourself.
Also, I am very excited by your mod and hope I can get it working. I use
many NPC mods and it would be so useful!! Keep up the great work.

**Comment by focustense** [comment]
The error itself indicates, not a problem with the race record itself, but an NPC that is pointing to a race record that doesn't exist.

I'll try to look into this soon, although since it involves downloading a 1.5 GB mod, it might not be right away. Thanks for reporting it, I'll update this as soon as I have more info.

**Comment by smbecket** [comment]
Sounds good, thanks!

**Comment by focustense** [comment]
Just installed this mod right now. The good news is, I can repro the issue, so it's definitely related to the mod. I was worried, because another user was reporting a similar issue with a custom-made merge that wasn't part of any mod I could find, but in this case installing the mod was enough. I'm now looking at specifics.

**Comment by focustense** [comment]
As I suspected, it is actually a problem with the mod. Or, if not a problem per se, something that is very unusual for a mod that I don't think it should be doing.

It changes the form list of `HeadPartsArgonian`, and adds to the list, not a race as would be expected, but a keyword (`KYWD`) pointing to `LolothSpider [KYWD:XX000D62]`. EasyNPC expects races in there, so it can't resolve it. The record exists, but points to something other than a race.

This reference, and any non-headpart references in the list, are irrelevant to EasyNPC, so I think a solution here is to just ignore them, or more specifically, fail silently when they can't be resolved. This would also skip actual race records that don't exist, but in practice, there's not really anything better we can do for those either.
