### ISSUE TITLE
Immersive weapons crash

### ISSUE THREAD

**Issue by rdhughes** [focustense/easymod#47]
Crashes on loading immersive weapons with:

```
2021-07-18 18:53:45.867 -05:00 [ERR] Exception was not handled
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.<>c.<ReadFaceTints>b__52_0(ITintLayerGetter x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.ReadFaceTints(INpcGetter npc)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.ReadFaceData(INpcGetter npc)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.GetFaceOverrides(INpcGetter npc, INpcGetter comparison, Boolean& affectsFaceGen)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.ReadNpcRecords(String pluginName, IDictionary`2 cache)
   at Focus.Apps.EasyNpc.Main.LoaderViewModel`1.GetNpcs()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Focus.Apps.EasyNpc.Main.LoaderViewModel`1.ConfirmPlugins()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Focus.Apps.EasyNpc.App.Main()
```

**Comment by focustense** [comment]
Edited post for formatting.

Looks straightforward. There are a few confusing references where Mutagen uses `IFoo` instead of `INullableFoo` for a reference, but is still actually nullable, and this looks like one of them.

Only thing is, I'm not sure _which_ reference it is - it could be the `Index`, the `Color` or the `Value`, log output doesn't get quite specific enough to say which. So I'll have to get this mod and check.

(I feel compelled to wonder aloud why "Immersive Weapons" is changing face tint layers... but I'm getting used to hearing about these.)

**Comment by focustense** [comment]
Unfortunately I've got a no-repro here - I went and picked up Immersive Weapons, but not seeing any error when loading it in the app. I can try to make some changes here and there that I think will solve it, but I'd prefer not to guess.

Are you positive that it's Immersive Weapons? What were the previous lines in the log file, that show which plugins are loading?

**Comment by rdhughes** [comment]
2021-07-18 18:53:39.604 -05:00 [INF] Initialized
2021-07-18 18:53:44.182 -05:00 [INF] Reading NPC records from Skyrim.esm...
2021-07-18 18:53:44.490 -05:00 [INF] Reading NPC records from Update.esm...
2021-07-18 18:53:45.259 -05:00 [INF] Reading NPC records from Dawnguard.esm...
2021-07-18 18:53:45.452 -05:00 [INF] Reading NPC records from HearthFires.esm...
2021-07-18 18:53:45.473 -05:00 [INF] Reading NPC records from Dragonborn.esm...
2021-07-18 18:53:45.513 -05:00 [INF] Reading NPC records from ccTWBSSE001-PuzzleDungeon.esm...
2021-07-18 18:53:45.521 -05:00 [INF] Reading NPC records from ccBGSSSE031-AdvCyrus.esm...
2021-07-18 18:53:45.528 -05:00 [INF] Reading NPC records from ccBGSSSE025-AdvDSGS.esm...
2021-07-18 18:53:45.531 -05:00 [INF] Reading NPC records from ccBGSSSE003-Zombies.esl...
2021-07-18 18:53:45.538 -05:00 [INF] Reading NPC records from ccBGSSSE004-RuinsEdge.esl...
2021-07-18 18:53:45.544 -05:00 [INF] Reading NPC records from ccBGSSSE019-StaffofSheogorath.esl...
2021-07-18 18:53:45.550 -05:00 [INF] Reading NPC records from ccBGSSSE018-Shadowrend.esl...
2021-07-18 18:53:45.552 -05:00 [INF] Reading NPC records from ccBGSSSE037-Curios.esl...
2021-07-18 18:53:45.552 -05:00 [INF] Reading NPC records from ccBGSSSE034-MntUni.esl...
2021-07-18 18:53:45.558 -05:00 [INF] Reading NPC records from ccBGSSSE008-Wraithguard.esl...
2021-07-18 18:53:45.563 -05:00 [INF] Reading NPC records from RSkyrimChildren.esm...
2021-07-18 18:53:45.565 -05:00 [INF] Reading NPC records from Unofficial Skyrim Special Edition Patch.esp...
2021-07-18 18:53:45.673 -05:00 [INF] Reading NPC records from Unofficial Skyrim Modders Patch.esp...
2021-07-18 18:53:45.693 -05:00 [INF] Reading NPC records from Unofficial Saints and Seducers Patch.esl...
2021-07-18 18:53:45.700 -05:00 [INF] Reading NPC records from Unofficial Rare Curios Patch.esl...
2021-07-18 18:53:45.700 -05:00 [INF] Reading NPC records from Unofficial Forgotten Seasons Patch.esl...
2021-07-18 18:53:45.700 -05:00 [INF] Reading NPC records from Unofficial Wild Horses Patch.esl...
2021-07-18 18:53:45.700 -05:00 [INF] Reading NPC records from Unofficial Dead Man's Dread Patch.esl...
2021-07-18 18:53:45.700 -05:00 [INF] Reading NPC records from Unofficial Shadowrend Patch.esl...
2021-07-18 18:53:45.700 -05:00 [INF] Reading NPC records from Unofficial Plague of the Dead Patch.esl...
2021-07-18 18:53:45.706 -05:00 [INF] Reading NPC records from Unofficial Sunder & Wraithguard Patch.esl...
2021-07-18 18:53:45.711 -05:00 [INF] Reading NPC records from Unofficial Staff of Sheogorath Patch.esl...
2021-07-18 18:53:45.711 -05:00 [INF] Reading NPC records from Unofficial Ruin's Edge Patch.esl...
2021-07-18 18:53:45.711 -05:00 [INF] Reading NPC records from Landscape and Water Fixes.esp...
2021-07-18 18:53:45.711 -05:00 [INF] Reading NPC records from Lightened Skyrim - merged.esp...
2021-07-18 18:53:45.711 -05:00 [INF] Reading NPC records from Diverse Random NormalAttack.esp...
2021-07-18 18:53:45.711 -05:00 [INF] Reading NPC records from Vibrant weapons.esl...
2021-07-18 18:53:45.712 -05:00 [INF] Reading NPC records from ImCh.esm...
2021-07-18 18:53:45.712 -05:00 [INF] Reading NPC records from BSAssets.esm...
2021-07-18 18:53:45.716 -05:00 [INF] Reading NPC records from BSHeartland.esm...
2021-07-18 18:53:45.792 -05:00 [INF] Reading NPC records from RaceCompatibility.esm...
2021-07-18 18:53:45.792 -05:00 [INF] Reading NPC records from RealisticWaterTwo - Resources.esm...
2021-07-18 18:53:45.792 -05:00 [INF] Reading NPC records from BS_DLC_patch.esp...
2021-07-18 18:53:45.792 -05:00 [INF] Reading NPC records from GRIM Wednesday Addams.esl...
2021-07-18 18:53:45.792 -05:00 [INF] Reading NPC records from FISS.esp...
2021-07-18 18:53:45.792 -05:00 [INF] Reading NPC records from AyleidCitadel.esp...
2021-07-18 18:53:45.793 -05:00 [INF] Reading NPC records from Heels Sound.esm...
2021-07-18 18:53:45.793 -05:00 [INF] Reading NPC records from dcc-soulgem-oven-000.esm...
2021-07-18 18:53:45.793 -05:00 [INF] Reading NPC records from DF_T19.esl...
2021-07-18 18:53:45.793 -05:00 [INF] Reading NPC records from [SunJeong] Dadg Clothing.esl...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from EFFCore.esm...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from High Poly Head.esm...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from Expressive Facegen Morphs.esl...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from DynDOLOD.esm...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from SkyUI_SE.esp...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from Audio Overhaul Skyrim.esp...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from Obsidian Weathers.esp...
2021-07-18 18:53:45.794 -05:00 [INF] Reading NPC records from SMIM-SE-Merged-All.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from ColonolNutty - Save My Stats.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [COCO] Succubus [SE].esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from VtawWardrobe5.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from 3BBB.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from BBD_RGENIE.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from Highheels.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from LsjDflmgpV1.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from VtawUtilityPack.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [Rektas] Temple Guardian [SE].esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from ComboCombat + Stances.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from EVGConditionalIdles.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from LandsInRoll.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [Christine] Aycroft Summer.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from CountHeavyArmor.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from Reduce Attack Scating Movement.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from Spells Knockback lite.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [Christine] Fun Gift.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [Rektas] Cortana [SE].esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from Fixed body collision.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from ImCh Less Papyrus Spam Patch.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from Skysan_Stalhrim.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [GarudaB]DOAXVV Twilight Time.esp...
2021-07-18 18:53:45.795 -05:00 [INF] Reading NPC records from [Christine] Arathia.esp...
2021-07-18 18:53:45.796 -05:00 [INF] Reading NPC records from Bathing in Skyrim - Main.esp...
2021-07-18 18:53:45.796 -05:00 [INF] Reading NPC records from H21353MSO.esp...
2021-07-18 18:53:45.796 -05:00 [INF] Reading NPC records from RelightingSkyrim_SSE.esp...
2021-07-18 18:53:45.796 -05:00 [INF] Reading NPC records from DepthsOfSkyrim.esp...
2021-07-18 18:53:45.796 -05:00 [INF] Reading NPC records from YamatoScbAction.esp...
2021-07-18 18:53:45.797 -05:00 [INF] Reading NPC records from Immersive Jewelry.esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from Bosmer Ceremonial as Glass.esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from H2135FantasySeries5.esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from H2135HalloweenOutfit2020.esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from H2135HalloweenOutfit2019.esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from HDT Female Hairstyles Wigs.esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from [COCO] Pinup Cheongsam [SE].esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from [Rektas] Dark Essence [SE].esp...
2021-07-18 18:53:45.798 -05:00 [INF] Reading NPC records from [NINI] Stellar Cancer.esp...
2021-07-18 18:53:45.799 -05:00 [INF] Reading NPC records from [NINI] Operator.esp...
2021-07-18 18:53:45.807 -05:00 [INF] Reading NPC records from Fresh Women.esp...
2021-07-18 18:53:45.857 -05:00 [INF] Reading NPC records from SimplyKnock.esp...
2021-07-18 18:53:45.857 -05:00 [INF] Reading NPC records from Immersive Weapons.esp...
2021-07-18 18:53:45.867 -05:00 [ERR] Exception was not handled
System.InvalidOperationException: Nullable object must have a value.

**Comment by rdhughes** [comment]
After some dinking around, I think this was due to me manually forwarding records in xedit between different overhauls and weapons mods. It would be useful if EasyNPC could flag the problem record(s) instead of crashing though.

**Comment by focustense** [comment]
Thanks for that update. Fair point about identifying the record - sometimes the error will do that, other times it won't.

The app has a debug mode in which logging is ramped up, so it could potentially log each NPC record before it is read, in addition to the plugin name which is always logged. That's going to generate a _lot_ of debug output, but then again the build already generates more output. I'll take your suggestion to add that - but users would still have to explicitly enable debug mode, I wouldn't want every user on every run getting 50 MB+ log files.

**Comment by rdhughes** [comment]
Great! That's going to be really useful as I try to figure out why male NPC overhaul is crashing EasyNPC now. It's flagging BOD2 records saying "unexpected with BOD2 type not expected on versions < 43", however these are form 44 records. But that's a totally different problem....
