### ISSUE TITLE
Something went wrong - crash!

### ISSUE THREAD

**Issue by andyseabrook007** [focustense/easymod#68]
Opened App - removed missing master issues
Pressed OK 
Crashed

This is Hotfix 0.8.7
Using Mod Manager 2

Windows Log
==============
Application: EasyNPC.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: RecordException RSkyrimChildren.esm => 001861:RSkyrimChildren.esm<FormList>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.GetValidRaces(IHeadPartGetter headPart)
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.<ReadHairRecords>b__35_1(IHeadPartGetter x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Focus.Apps.EasyNpc.Main.LoaderViewModel`1.ConfirmPlugins()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()

EasyNPC ErrorLog
   at [Log_20210723_162702_3954236.txt](https://github.com/focustense/easymod/files/6869808/Log_20210723_162702_3954236.txt)

**Comment by focustense** [comment]
Is that the whole app log? It seems like quite a bit of it has been cut out, I don't even see it loading from Skyrim.esm before it gets to RS Children. Not only can I not see which NPC it's trying to process, I can't even see which _plugin_ it's trying to process.

I have the latest version of that mod and it gets processed OK, so I don't think it's a problem with that mod. (There _are_ problems with that mod, which is why 0.8.7 ignores children, but not _crash_ problems like this one.)

Could you please run in debug mode one time (add `--debug` to the command-line arguments in the MO2 executable) and post the whole log afterward so we can see which plugin and/or NPC is causing the problem? It looks to me like maybe you're running an old patch for RS Children, or a new patch on an old version of RS Children, and it's pointing to a record in RS Children that doesn't exist.
