### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by gn01036238** [focustense/easymod#81]
[Log_20210731_144424_4460098.txt](https://github.com/focustense/easymod/files/6910822/Log_20210731_144424_4460098.txt)

**Comment by focustense** [comment]
Stack trace is:

```
RecordException B&B.esp => 000D69:B&B.esp<TextureSet>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 setup)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.ImportHeadPartDependencies(HeadPart headPart)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.<Import>b__8_0[T,TGetter](T x)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group, Action`1 setup)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.MergeContext.Import[T,TGetter](IFormLinkGetter`1 link, IGroup`1 group)
   at Focus.Apps.EasyNpc.Mutagen.MutagenMergedPluginBuilder.Build(IReadOnlyList`1 npcs, BuildSettings`1 buildSettings, ProgressViewModel progress)
```

This plugin (`B&B.esp`) has a broken NPC record - one of them is pointing to a texture set that doesn't exist.

This actually should have been fixed by b23b37b1c0fc3d7553bb538be49f6937f2a66b90, so I'll take a look and see why it's crashing, but even if I fix the bug, the textures won't be correct on this NPC because the plugin itself does not have the required texture set record.

If you can track down which NPC is pointing to `000D69`, e.g. in xEdit, and confirm that it is in fact an invalid ref, then you should report that to the author of the mod.

**Comment by focustense** [comment]
I haven't seen any updates here, and haven't encountered anything that sheds light on it yet, so I may close this as non repro. If you can tell me which mod this B&B plugin came from, then I can take a closer look at that mod and maybe get a better chance at fixing (to the extent that this is really fixable).

**Comment by gn01036238** [comment]
I'm not familiar with xEdit so don't really know how to track down which npc is pointing 000d69 texture, did some exhaustive search with my own eyes and didn't find it
Here's the link to the mod
[](https://arca.live/b/tullius/4931139?mode=best&target=all&keyword=b%26b&p=1)
You might need VPN to be able to view the content so here's the direct link to it
[Google Drive](https://drive.google.com/file/d/1lvlqSyIIl1TspFOWykuQaw9JOEDWLmWH/view)

**Comment by focustense** [comment]
As of [v0.9.3](https://github.com/focustense/easymod/releases/tag/v0.9.3), there is now a reference checker (#107) which runs on startup and should provide what I hope is very clear guidance on where the errors are. NPC options with invalid references will be disabled in the profile, so they can't be selected and subsequently break the build.

Because this now exists, I'm closing all prior issues related to invalid references. Please report any bugs or other problems you find with the reference checker in a new GitHub issue. Thanks!
