### ISSUE TITLE
Crash while running build

### ISSUE THREAD

**Issue by mckq2ooo** [focustense/easymod#84]
[Log_20210808_122535_7498798.txt](https://github.com/focustense/easymod/files/6950512/Log_20210808_122535_7498798.txt)

**Comment by focustense** [comment]
You have part of your profile pointing to a mod that doesn't exist.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Modding\MO2\mods\Bijin NPCs SE 1.2.1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Focus.Apps.EasyNpc.Build.MergedFolder.<>c__1`1.<Build>b__1_9(String modPath)
```

#50, once implemented, will block builds so that people don't get surprised by this. In the meantime, the build warning screen prior to the build attempt should be telling you which NPCs need to be fixed. A lot of warnings can sometimes be ignored but "invalid mod" is always fatal.
